server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Перенаправляем все запросы на index.html для работы роутинга во Flutter
        try_files $uri $uri/ /index.html;
    }
}